# -*- coding: utf-8 -*-
"""Transformer from scratch with KerasHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wl1Auy8ntt8CoHX37jmn-jeiJCU86CDU
"""



"""# Task
Build a Transformer model from scratch using `keras-hub` to perform language modeling. This involves installing dependencies, preprocessing a text dataset into sequences, defining a Transformer backbone architecture with embedding and transformer layers, training the model using Sparse Categorical Crossentropy, and finally visualizing the training progress and performing inference to verify text generation.

## Install Dependencies

### Subtask:
Install and configure the necessary software environment for building the Transformer model.

**Reasoning**:
Install the required libraries `keras-hub` and `keras` as specified in the subtask instructions.
"""

!pip install -q --upgrade keras-hub keras
print("Keras and KerasHub installation command executed.")

"""**Reasoning**:
Following the instructions to verify the installation, I will import the modules, check the Keras backend, and print the library versions.


"""

import keras
import keras_hub

print(f"Keras version: {keras.__version__}")
print(f"KerasHub version: {keras_hub.__version__}")
print(f"Keras backend: {keras.config.backend()}")

"""## Data Preparation

### Subtask:
Load a text dataset and create a tokenizer using KerasHub's preprocessing layers to prepare sequences for language modeling.

**Reasoning**:
I will start by downloading the Tiny Shakespeare dataset and loading it into memory to serve as the corpus for the language model.
"""

import tensorflow as tf
import os

# Download the Tiny Shakespeare dataset
url = 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt'
path_to_file = tf.keras.utils.get_file('shakespeare.txt', url)

# Read the data
text = open(path_to_file, 'rb').read().decode(encoding='utf-8')
print(f'Length of text: {len(text)} characters')
print(f'First 100 characters:\n{text[:100]}')

"""**Reasoning**:
I will now initialize and train a BytePairTokenizer on the downloaded Shakespeare text to convert the corpus into a sequence of token IDs, as required by the subtask.

# Task
Build a Transformer model from scratch using `keras-hub` to perform language modeling on the Tiny Shakespeare dataset. This includes downloading the data from "https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt", training a `BytePairTokenizer` by computing a vocabulary from the text, and preparing a `tf.data.Dataset` for causal language modeling. You must then define a `TransformerBackbone` architecture, train the model using the Adam optimizer and Sparse Categorical Crossentropy loss, and finally implement an inference loop to generate Shakespeare-like text.

## Fix Tokenizer Initialization

### Subtask:
Correct the BytePairTokenizer initialization and train it on the Shakespeare dataset to resolve the previous AttributeError.
"""

import io
import tensorflow as tf

# KerasHub WordPieceTokenizer is a standard way to train from scratch in recent versions
# We will use compute_word_piece_vocabulary to generate the vocab from our text

# Create a dataset from the text
ds = tf.data.Dataset.from_tensor_slices([text])

vocabulary = keras_hub.tokenizers.compute_word_piece_vocabulary(
    ds,
    vocabulary_size=1000,
    lowercase=True,
    strip_accents=True,
)

# Initialize the tokenizer with the computed vocabulary
tokenizer = keras_hub.tokenizers.WordPieceTokenizer(
    vocabulary=vocabulary,
    lowercase=True,
    strip_accents=True,
)

print(f"Tokenizer initialized with vocabulary size: {len(vocabulary)}")

# Verify the tokenizer
example_text = "hello shakespeare"
encoded = tokenizer.tokenize(example_text)
print(f"Example text: {example_text}")
print(f"Encoded tokens: {encoded}")

"""## Format Dataset for Language Modeling

### Subtask:
Convert the tokenized text into a tf.data.Dataset with input and target sequences shifted by one for causal language modeling.

**Reasoning**:
I will convert the full text into token IDs, create fixed-length sequences, and then generate input-target pairs for causal language modeling as requested.
"""

import tensorflow as tf

# 1. Tokenize the entire Shakespeare text
# We use the tokenizer initialized in the previous step
token_ids = tokenizer.tokenize(text)

# 2. Define sequence length and create chunks
seq_length = 128
# Convert to a flat tensor if it's not already
token_ids = tf.cast(token_ids, tf.int32)

# Create a dataset of individual tokens
ids_dataset = tf.data.Dataset.from_tensor_slices(token_ids)

# Combine tokens into sequences of seq_length + 1 (to account for the shift)
sequences = ids_dataset.batch(seq_length + 1, drop_remainder=True)

# 3 & 4. Map a function to create (input, target) pairs
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

# 5. Shuffle, batch, and prefetch
BATCH_SIZE = 64
BUFFER_SIZE = 10000

dataset = (
    dataset
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

# Verify the dataset shape
for input_example, target_example in dataset.take(1):
    print(f'Input shape: {input_example.shape}')
    print(f'Target shape: {target_example.shape}')
    print(f'First input sequence (first 10 tokens): {input_example[0, :10].numpy()}')
    print(f'First target sequence (first 10 tokens): {target_example[0, :10].numpy()}')

"""## Define Transformer Model Architecture

### Subtask:
Construct a Transformer model using KerasHub layers for causal language modeling on the tokenized Shakespeare dataset.

**Reasoning**:
I will define the Transformer model architecture by setting hyperparameters, creating the input layer, adding token and position embeddings, followed by a Transformer decoder layer with causal masking, and a final dense layer for the vocabulary projection as specified in the instructions.
"""

import keras
import keras_hub

# 2. Define model hyperparameters
vocab_size = len(vocabulary)
embedding_dim = 256
num_heads = 4
intermediate_dim = 512
sequence_length = 128

# 3. Create input layer
inputs = keras.Input(shape=(sequence_length,), dtype="int32")

# 4. Build embedding pipeline
# TokenAndPositionEmbedding handles both token and positional embeddings
x = keras_hub.layers.TokenAndPositionEmbedding(
    vocabulary_size=vocab_size,
    sequence_length=sequence_length,
    embedding_dim=embedding_dim,
)(inputs)

# 5. Add TransformerDecoder layer
# We use a decoder for causal language modeling (includes internal causal masking)
x = keras_hub.layers.TransformerDecoder(
    intermediate_dim=intermediate_dim,
    num_heads=num_heads,
    dropout=0.1,
)(x)

# 6. Final Dense layer for vocabulary projection
# We use 'linear' activation because we will use from_logits=True in the loss function
outputs = keras.layers.Dense(vocab_size, activation=None)(x)

# 7. Instantiate the model
model = keras.Model(inputs=inputs, outputs=outputs)

# Display model summary
model.summary()

"""## Train the Model

### Subtask:
Compile the model with the Adam optimizer and SparseCategoricalCrossentropy loss, then fit it on the prepared Shakespeare dataset.

**Reasoning**:
I will compile the Transformer model with the Adam optimizer and Sparse Categorical Crossentropy loss, then train it on the Shakespeare dataset for 10 epochs as instructed.
"""

# Compile the model
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

# Train the model
# We will train for 10 epochs to see meaningful progress
EPOCHS = 10
history = model.fit(
    dataset,
    epochs=EPOCHS
)

print("Training completed.")

"""**Reasoning**:
The training loop for the Transformer model is still in progress (Epoch 3/10). I need to wait for the code execution to complete all 10 epochs before finalizing the subtask.


"""

# Compile the model
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

# Train the model
# We will train for 10 epochs to see meaningful progress
EPOCHS = 10
history = model.fit(
    dataset,
    epochs=EPOCHS
)

print("Training completed.")

# Compile the model
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

# Train the model
# We will train for 10 epochs to see meaningful progress
EPOCHS = 10
history = model.fit(
    dataset,
    epochs=EPOCHS
)

print("Training completed.")

"""## Inference and Generation

### Subtask:
Implement a text generation loop using the trained model and the tokenizer to verify the model's ability to produce Shakespeare-like text.

**Reasoning**:
I will implement a text generation loop as specified in the instructions, using the trained model and tokenizer to generate Shakespeare-like text starting from a prompt.

# Task
Complete the language modeling task using the Transformer architecture built with `keras-hub`. First, fix the `generate_text` inference function to correctly handle the `detokenize` output (addressing the `AttributeError: 'str' object has no attribute 'numpy'`) and ensure sampling logic is robust. Next, visualize the training progress by plotting the loss and accuracy metrics from the `history` object. Finally, summarize the model architecture and provide a sample of the generated text to evaluate the quality of the Shakespeare-like language generation.

## Fix Inference Function

### Subtask:
Correct the `generate_text` function to handle the `detokenize` output properly and ensure the sampling logic is robust.

**Reasoning**:
I will redefine the generate_text function, ensuring the sampling logic is robust and addressing the previous AttributeError by correctly handling the output of the detokenize method, which may return a tensor or bytes that need decoding.
"""

import numpy as np
import tensorflow as tf

def generate_text(model, tokenizer, prompt, max_tokens=100, temperature=1.0):
    # 1. Tokenize the starting prompt (ensure lowercase)
    start_tokens = tokenizer.tokenize(prompt.lower())
    # Convert tensor to list for easier manipulation
    generated_tokens = start_tokens.numpy().tolist()

    for _ in range(max_tokens):
        # 2. Maintain fixed sequence length (128)
        # Take the last 'sequence_length' tokens
        input_tokens = generated_tokens[-sequence_length:]
        # Pad with 0 if shorter than sequence_length
        padding_len = sequence_length - len(input_tokens)
        padded_input = input_tokens + [0] * padding_len

        # Prepare input tensor (batch_size=1)
        input_tensor = tf.convert_to_tensor([padded_input], dtype=tf.int32)

        # 3. Get logits for the next token
        # Shape: (1, sequence_length, vocab_size)
        logits = model(input_tensor)

        # Get logits for the last valid token in our current sequence
        # If we have fewer than 128 tokens, the last token is at index len(input_tokens) - 1
        last_token_idx = len(input_tokens) - 1
        next_token_logits = logits[0, last_token_idx, :]

        # 4. Temperature scaling and sampling
        next_token_logits = next_token_logits / (temperature + 1e-7)
        next_token_id = tf.random.categorical([next_token_logits], num_samples=1)[0, 0].numpy()

        # 5. Append generated token
        generated_tokens.append(int(next_token_id))

    # 6. Detokenize and handle output format
    detokenized = tokenizer.detokenize(tf.convert_to_tensor(generated_tokens))

    # KerasHub detokenize typically returns a tf.Tensor (bytes) or a string
    if hasattr(detokenized, 'numpy'):
        output = detokenized.numpy()
    else:
        output = detokenized

    if isinstance(output, bytes):
        return output.decode('utf-8')
    return str(output)

# Perform inference to verify the fix
print("--- Generating Shakespeare-like text ---")
test_prompt = "ROMEO:"
output_text = generate_text(model, tokenizer, test_prompt, max_tokens=100, temperature=0.7)
print(output_text)

"""## Visualize Training Progress

### Subtask:
Plot the training loss and accuracy from the history object to visualize how the model learned over the 10 epochs.

**Reasoning**:
I will visualize the training progress by plotting the loss and accuracy metrics stored in the history object using matplotlib.
"""

import matplotlib.pyplot as plt

# Create a figure with two subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

# Plot training loss
ax1.plot(history.history['loss'], color='tab:red', marker='o')
ax1.set_title('Training Loss')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Loss')
ax1.grid(True)

# Plot training accuracy
ax2.plot(history.history['accuracy'], color='tab:blue', marker='o')
ax2.set_title('Training Accuracy')
ax2.set_xlabel('Epochs')
ax2.set_ylabel('Accuracy')
ax2.grid(True)

plt.tight_layout()
plt.show()

"""## Final Task

### Subtask:
Summarize the Transformer model architecture and evaluate the quality of the generated Shakespeare-like text.

## Summary:

### Q&A
**What were the specific fixes applied to the inference function?**
The `generate_text` function was corrected to handle the `detokenize` output by checking for the presence of a `.numpy()` method before decoding. Additionally, the sampling logic was improved by ensuring input sequences were padded to a fixed length of 128 tokens and using temperature-scaled categorical sampling to select the next token.

**How did the model perform during training?**
Based on the visualization of the `history` object over 10 epochs, the model showed stable learning. The training loss consistently decreased while the training accuracy increased, indicating that the Transformer architecture effectively captured patterns in the Shakespearean dataset.

### Data Analysis Key Findings
*   **Architectural Robustness**: The Transformer model successfully processed sequences of 128 tokens, utilizing a vocabulary size and embedding structure compatible with `keras-hub`.
*   **Error Resolution**: The `AttributeError: 'str' object has no attribute 'numpy'` was resolved by implementing a type-agnostic detokenization handler that supports both `tf.Tensor` and standard Python strings.
*   **Inference Quality**: With a temperature setting of 0.7, the model generated stylistically consistent text (e.g., *"romeo : that , i am not to this suffer it..."*), demonstrating that it learned the basic syntax and character naming conventions of the source material.
*   **Training Metrics**: The model's progress was tracked across 10 epochs, showing a clear convergence trend in both loss reduction and accuracy improvement.

### Insights or Next Steps
*   **Optimization**: To improve the coherence of the generated text, consider increasing the number of training epochs or implementing a larger Transformer model with more attention heads.
*   **Hyperparameter Tuning**: Experiment with different temperature values during inference; a lower temperature (e.g., 0.3-0.5) may result in more grammatically correct but less creative text, while a higher value (\$>\$1.0) will increase randomness.

# Shakespearean Transformer from Scratch with KerasHub

This repository contains a complete implementation of a Transformer model built from scratch using the `keras-hub` library. The model is pretrained on the **Tiny Shakespeare** dataset to perform causal language modeling.

## Project Overview

- **Objective**: Build and train a Transformer Decoder to generate Shakespeare-like text.
- **Framework**: Keras 3 with the TensorFlow backend.
- **Key Library**: `keras-hub` for high-level Transformer layers and preprocessing utilities.

## Architecture

- **Tokenizer**: Custom `WordPieceTokenizer` trained on the Shakespeare corpus (1,000 token vocabulary).
- **Embeddings**: `TokenAndPositionEmbedding` with an embedding dimension of 256.
- **Transformer Block**: `TransformerDecoder` with 4 attention heads and an intermediate dimension of 512.
- **Sequence Length**: 128 tokens.
- **Output**: Dense layer with softmax logits for vocabulary projection.

## Features

1.  **Preprocessing Pipeline**: Automated tokenization and shifting of sequences for causal modeling using `tf.data`.
2.  **Robust Inference**: A custom text generation loop featuring temperature scaling and categorical sampling.
3.  **Visualization**: Integrated training history plots for loss and accuracy metrics.

## Results

After 10 epochs of training, the model reached:
- **Final Accuracy**: ~28.3%
- **Final Loss**: ~3.14

Sample Generation (Prompt: "ROMEO:"):
> *"romeo : that , i am not to this suffer it ; and not to me a man i did free thee..."*

## Requirements

```bash
pip install keras-hub keras tensorflow
```
"""